version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - "mongodbdata:/data/db"
    ports:
      - '27017:27017'
    networks:
      - net
  rabbitmq: # login guest:guest
    image: rabbitmq:management
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - net
  api:
    image: jktechapi:v2
    environment:
      - HOSTNAMERABBIT=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongo
    links:
      - rabbitmq
      - mongo
    ports:
      - '5000:80'
    networks:
      - net
networks:
  net:
volumes:
  mongodbdata:
    external: true